services:
  # nanti setiap db nya kan pasti bakal banyak, bikin aja kek user-db, tambahin depends on & environment (DB URL) kek user-service.
  # make sure di db service backend codenya pake DATABASE_URL environment variable untuk koneksi ke database
  # jgn lupa bikin volume untuk persist data
  user-db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: user_service_db
    ports:
      - "5433:5432"
    volumes:
      - user-db-data:/var/lib/postgresql/data
    networks:
      - app-network

  video-db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: video_service_db
    ports:
      - "5434:5432"
    volumes:
      - video-db-data:/var/lib/postgresql/data
    networks:
      - app-network

  envoy:
    image: envoyproxy/envoy:v1.29-latest
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
    ports:
      - 8080:8080
      - 9901:9901
    depends_on:
      - auth-service
      - user-service
      - video-service
    networks:
      - app-network
    # optional explicit command:
    # command: ["-c", "/etc/envoy/envoy.yaml"]

  memcached:
    image: memcached:1.6-alpine
    ports:
      - "11211:11211"
    networks:
      - app-network

  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"   # S3 API
      - "9001:9001"   # Web UI
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data
    networks:
      - app-network

  user-service:
    build: 
      context: ./backend
      dockerfile: user-service/Dockerfile
    depends_on:
      - user-db
    environment:
      DATABASE_URL: postgres://postgres:postgres@user-db:5432/user_service_db
    ports:
      - 50051:50051
    networks:
      - app-network

  auth-service:
    build: 
      context: ./backend
      dockerfile: auth-service/Dockerfile
    ports:
      - 50052:50052
    depends_on:
      - user-service
      - memcached
    environment:
      MEMCACHED_HOST: memcached:11211
      SMTP_USER: tpawebkn@gmail.com
      SMTP_PASS: dwjb nfyf usuq qhuz
      SMTP_HOST: smtp.gmail.com
      SMTP_PORT: 587
    networks:
      - app-network

  video-service:
    build: 
      context: ./backend
      dockerfile: video-service/Dockerfile
    ports:
      - 50053:50053
    depends_on:
      - video-db
      - minio
      - user-service
    environment:
      DATABASE_URL: postgres://postgres:postgres@video-db:5432/video_service_db
      MINIO_ENDPOINT: minio:9000
      MINIO_PUBLIC_URL: localhost:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      MINIO_BUCKET: videos
    networks:
      - app-network
    
  frontend:
    build: ./frontend
    ports:
      - 3000:80
    networks:
      - app-network

volumes:
  user-db-data:
  video-db-data:
  minio-data:

networks:
  app-network:
    driver: bridge