services:
  # nanti setiap db nya kan pasti bakal banyak, bikin aja kek user-db, tambahin depends on & environment (DB URL) kek user-service.
  # make sure di db service backend codenya pake DATABASE_URL environment variable untuk koneksi ke database
  # jgn lupa bikin volume untuk persist data
  user-db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: user_service_db
    ports:
      - "5433:5432"
    volumes:
      - user-db-data:/var/lib/postgresql/data
    networks:
      - app-network

  envoy:
    image: envoyproxy/envoy:v1.29-latest
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
    ports:
      - 8080:8080
      - 9901:9901
    depends_on:
      - auth-service
      - user-service
    networks:
      - app-network
    # optional explicit command:
    # command: ["-c", "/etc/envoy/envoy.yaml"]

  auth-service:
    build: 
      context: ./backend
      dockerfile: auth-service/Dockerfile
    ports:
      - 50052:50052
    depends_on:
      - user-service
    networks:
      - app-network

  user-service:
    build: 
      context: ./backend
      dockerfile: user-service/Dockerfile
    depends_on:
      - user-db
    environment:
      DATABASE_URL: postgres://postgres:postgres@user-db:5432/user_service_db
    ports:
      - 50051:50051
    networks:
      - app-network

  frontend:
    build: ./frontend
    ports:
      - 3000:80
    networks:
      - app-network

volumes:
  user-db-data:

networks:
  app-network:
    driver: bridge