# syntax=docker/dockerfile:1
FROM golang:1.24.4-alpine

WORKDIR /app

# Install git, curl, wget, and Air
RUN apk update && apk add --no-cache git curl wget && \
    go install github.com/air-verse/air@v1.62.0

# Copy go.mod and go.sum for dependency resolution
COPY favorite-service/go.mod favorite-service/go.sum ./favorite-service/

# Copy .air.toml config file into /app/favorite-service
COPY favorite-service/.air.toml ./favorite-service/

# Copy shared package
COPY shared ./shared

# Copy middleware package
COPY middleware ./middleware

# Create folder placeholders (will be mounted in docker-compose)
RUN mkdir -p /app/shared /app/middleware /app/favorite-service

# Set working directory to service
WORKDIR /app/favorite-service

# Pre-download Go dependencies
RUN go mod download

# Install grpc_health_probe
RUN GRPC_HEALTH_PROBE_VERSION=v0.4.25 && \
    wget -qO /usr/local/bin/grpc_health_probe https://github.com/grpc-ecosystem/grpc-health-probe/releases/download/${GRPC_HEALTH_PROBE_VERSION}/grpc_health_probe-linux-amd64 && \
    chmod +x /usr/local/bin/grpc_health_probe

# Expose app port
EXPOSE 50059

# Run Air for hot reload
CMD ["air"]
