
syntax = "proto3";

package activity;

option go_package = "github.com/KennedySurianto/tpa_web/backend/shared/gen/follow;follow";

import "user.proto";

service FollowService {
    rpc Follow(FollowRequest) returns (Empty) {}
    rpc Unfollow(FollowRequest) returns (Empty) {}
    rpc GetFollowers(UserRequest) returns (FollowList) {}
    rpc GetFollowing(UserRequest) returns (FollowList) {}
    rpc GetFriends(GetFriendsRequest) returns (GetFriendsResponse);
}

message GetFriendsRequest {
    string user_id = 1;   // The ID of the user for whom we are fetching the friends
    int32 page = 2;       // The current page number
    int32 limit = 3;      // The number of friends to return per page
}

// Define the message for the response
message GetFriendsResponse {
    repeated user.User users = 1;  // List of friends (User objects)
    bool has_more = 2;        // Flag to indicate if more friends are available
}

message FollowRequest {
    uint32 follower_id = 1;
    uint32 followed_id = 2;
}

message UserRequest {
    uint32 user_id = 1;
}

message FollowItem {
    uint32 follower_id = 1;
    uint32 followed_id = 2;

    user.User user = 3; // kalo get followers, kasi follower. kalo get following, kasi following.
}

message FollowList {
    repeated FollowItem follows = 1;
}

message Empty {}
