syntax = "proto3";

package playlist;

option go_package = "github.com/KennedySurianto/tpa_web/backend/shared/gen/playlist;playlist";

import "google/protobuf/timestamp.proto";

service PlaylistService {
	rpc CreatePlaylist (CreatePlaylistRequest) returns (CreatePlaylistResponse);
	rpc GetPlaylist (GetPlaylistRequest) returns (Playlist);
	rpc GetPlaylistsByUserId (GetPlaylistRequest) returns (GetPlaylistByUserIdResponse);
	rpc DeletePlaylist (DeletePlaylistRequest) returns (DeletePlaylistResponse);
}

message CreatePlaylistRequest {
	string name = 1;
	uint64 user_id = 2;
	repeated uint64 video_ids = 3;
}

message CreatePlaylistResponse {
	uint64 playlist_id = 1;
}

message GetPlaylistRequest {
	uint64 id = 1;
}

message User {
	uint64 id = 1;
	string username = 2;
	bytes avatar = 3;
}

message Video {
	uint32 id = 1;
	google.protobuf.Timestamp created_at = 2;
	google.protobuf.Timestamp updated_at = 3;
	google.protobuf.Timestamp deleted_at = 4;
	
	// Video metadata
	uint32 user_id = 5;
	string video_url = 6;
	bytes thumbnail = 7;
	string caption = 8;
	optional string description = 9;
	int32 duration = 10;
	
	// Optional associations
	optional uint32 sound_id = 11;
	string privacy = 12;
	
	// Cached metrics
	uint32 views_count = 13;
	uint32 likes_count = 14;
	uint32 comments_count = 15;
	
	// Feature flags
	bool allow_comments = 16;
	bool allow_duet = 17;
	bool allow_stitch = 18;

	User user = 19;

	bool is_liked = 20;
	uint64 like_count = 21;
}

message Playlist {
    uint64 id = 1;
    string name = 2;
    uint64 user_id = 3;
    repeated Video videos = 4;
    google.protobuf.Timestamp created_at = 5;
    google.protobuf.Timestamp updated_at = 6;
    google.protobuf.Timestamp deleted_at = 7;
}

message GetPlaylistByUserIdResponse {
	repeated Playlist playlists = 1;
}

message DeletePlaylistRequest {
	uint64 id = 1;
}

message DeletePlaylistResponse {
	bool success = 1;
}
